// 兼容层：旧代码仍可从 src/lib/api.js 导入。
export {
  fetchDashboard,
  fetchDashboardStatus,
  fetchDevices,
  fetchTasks,
  runTaskOnce,
  saveConfig,
  rerollSchedule,
  runDoctor,
  restartAdb,
  runOnce,
  startScheduler,
  stopScheduler,
  fetchLogs,
  fetchCheckinRecords,
  addCheckinRecord,
  deleteCheckinRecord,
  login,
  logout,
  fetchHealth,
} from "../api";
